import 'package:get/get_navigation/src/root/internacionalization.dart';

class Languages extends Translations{
  @override
  Map<String, Map<String, String>> get keys => {
  'en_US': {
  'AppBar_Title' : "TOSBI",
    'AppBar_DrawerTitle' : "SAVED TOSBIS",
    'Light_Mode' : "Light Mode",
    'Dark_Mode' : "Dark Mode",
    'Language': "Language",
    'Version': "Version 1.0",
    'TextField_Title': "Enter Tosbi Name",
    'TextField_Error_Text' : "Enter your tosbi name",
    'HintText': "Type",
    'Button_Text': "Save",
    'Delete_Tosbi_Text': "Do you want to delete tosbi?",
    'Delete_Tosbi_Text2': "Do you want to delete all tosbi?",
    'Reset_Text': "Once Reset, You can't undo",
    'Decrease_Count': "Decrease Count",
    'Switch_Text': "Do you want to switch?\n",
    'Switch_Warning': "\n(Save before switching, otherwise current Tosbi count will be delete)",
    'TosbiOfAllahName': "Do you want to count?",
    "Allah's99Name": "Allah 99 Name's",
    "Saved": "Is Saved",
    "DeleteAll": "Delete All Tosbis",
  },
    'bn_BD': {
      'AppBar_Title' : "তসবী",
      'AppBar_DrawerTitle' : "সংরক্ষিত তসবী",
      'Light_Mode' : "লাইট মুড",
      'Dark_Mode' : "ডার্ক মুড",
      'Language': "ভাষা",
      'Version' : "ভার্সন ১.০",
      'TextField_Title': "তসবীর নাম লিখুন",
      'TextField_Error_Text': "আগে তসবীর নাম লিখুন",
      'HintText': "লিখুন",
      'Button_Text': "সংরক্ষণ",
      'Delete_Tosbi_Text': "আপনি কি তসবী মুছে ফেলতে চান?",
      'Delete_Tosbi_Text2': "আপনি কি সব তসবী মুছে ফেলতে চান?",
      'Reset_Text': "একবার গণনা মুছার পর তা আর ফিরত আসবে না",
      'Decrease_Count': "গণনা কমান",
      'Switch_Text': "আপনি কি সংরক্ষিত তসবীতে যেতে চান?\n",
      'Switch_Warning': "\n(বর্তমান তসবীটি হারিয়ে যাবে, যদি না আগে তা সংরক্ষণ করেন)",
      'TosbiOfAllahName': "আপনি কি গণনা শুরু করতে চান?",
      "Allah's99Name": "আল্লাহর ৯৯টি নাম",
      "Saved": "সংরক্ষণ হয়েছে",
      "DeleteAll": "সব তসবী মুছুন",
    }
};
  final Map<String, String> engToBangla = {
    '0': '০',
    '1': '১',
    '2': '২',
    '3': '৩',
    '4': '৪',
    '5': '৫',
    '6': '৬',
    '7': '৭',
    '8': '৮',
    '9': '৯',
  };
}
final List<Map<String, String>> allah99Names = [
  {"bangla": "আর রাহমান", "english": "AR-RAHMAAN"},
  {"bangla": "আর-রাহীম", "english": "AR-RAHEEM"},
  {"bangla": "আল-মালিক", "english": "AL-MALIK"},
  {"bangla": "আল-কুদ্দুস", "english": "AL-QUDDUS"},
  {"bangla": "আস-সালাম", "english": "AS-SALAM"},
  {"bangla": "আল-মু'মিন", "english": "AL-MU’MIN"},
  {"bangla": "আল-মুহাইমিন", "english": "AL-MUHAYMIN"},
  {"bangla": "আল-আ'জীজ", "english": "AL-AZEEZ"},
  {"bangla": "আল-জাব্বার", "english": "AL-JABBAR"},
  {"bangla": "আল-মুতাকাব্বিইর", "english": "AL-MUTAKABBIR"},
  {"bangla": "আল-খালিক্ব", "english": "AL-KHAALIQ"},
  {"bangla": "আল-বারী", "english": "AL-BAARI’"},
  {"bangla": "আল-মুছউইর", "english": "AL-MUSAWWIR"},
  {"bangla": "আল-গফ্ফার", "english": "AL-GHAFFAR"},
  {"bangla": "আল-ক্বাহার", "english": "AL-QAHHAR"},
  {"bangla": "আল-ওয়াহ্হাব", "english": "AL-WAHHAAB"},
  {"bangla": "আর-রজ্জাক্ব", "english": "AR-RAZZAAQ"},
  {"bangla": "আল ফাত্তাহ", "english": "AL-FATTAAH"},
  {"bangla": "আল-আ'লীম", "english": "AL-‘ALEEM"},
  {"bangla": "আল-ক্ববিদ্ব'", "english": "AL-QAABID"},
  {"bangla": "আল-বাসিত", "english": "AL-BAASIT"},
  {"bangla": "আল-খফিদ্বু", "english": "AL-KHAAFIDH"},
  {"bangla": "আর-রফীই'", "english": "AR-RAAFI’"},
  {"bangla": "আল-মুই'জ্ব", "english": "AL-MU’IZZ"},
  {"bangla": "আল-মুদ্বি'ল্লু (আল-মুযিল্ল)", "english": "AL-MUZIL"},
  {"bangla": "আস্-সামিই'", "english": "AS-SAMEE’"},
  {"bangla": "আল-বাছীর", "english": "AL-BASEER"},
  {"bangla": "আল-হা'কাম", "english": "AL-HAKAM"},
  {"bangla": "আল-আ'দল", "english": "AL-‘ADL"},
  {"bangla": "আল-লাতীফ", "english": "AL-LATEEF"},
  {"bangla": "আল-খ'বীর", "english": "AL-KHABEER"},
  {"bangla": "আল-হা'লীম", "english": "AL-HALEEM"},
  {"bangla": "আল-আ'জীম", "english": "AL-‘AJHEEM"},
  {"bangla": "আল-গফুর", "english": "AL-GHAFOOR"},
  {"bangla": "আশ্-শাকুর", "english": "ASH-SHAKOOR"},
  {"bangla": "আল-আ'লিইউ", "english": "AL-‘ALEE"},
  {"bangla": "আল-কাবিইর", "english": "AL-KABEER"},
  {"bangla": "আল-হা'ফীজ", "english": "AL-HAFEEDH"},
  {"bangla": "আল-মুক্বীত", "english": "AL-MUQEET"},
  {"bangla": "আল-হাসীব", "english": "AL-HASEEB"},
  {"bangla": "আল-জালীল", "english": "AL-JALEEL"},
  {"bangla": "আল-কারীম", "english": "AL-KAREEM"},
  {"bangla": "আর-রক্বীব", "english": "AR-RAQEEB"},
  {"bangla": "আল-মুজীব", "english": "AL-MUJEEB"},
  {"bangla": "আল-ওয়াসি'", "english": "AL-WAASI’"},
  {"bangla": "আল-হাকীম", "english": "AL-HAKEEM"},
  {"bangla": "আল-ওয়াদুদ", "english": "AL-WADOOD"},
  {"bangla": "আল-মাজীদ", "english": "AL-MAJEED"},
  {"bangla": "আল-বাই'ছ'", "english": "AL-BA’ITH"},
  {"bangla": "আশ্-শাহীদ", "english": "ASH-SHAHEED"},
  {"bangla": "আল-হা'ক্ব", "english": "AL-HAQQ"},
  {"bangla": "আল-ওয়াকিল", "english": "AL-WAKEEL"},
  {"bangla": "আল-ক্বউইউ", "english": "AL-QAWIYY"},
  {"bangla": "আল-মাতীন", "english": "AL-MATEEN"},
  {"bangla": "আল-ওয়ালিইউ", "english": "AL-WALIYY"},
  {"bangla": "আল-হা'মীদ", "english": "AL-HAMEED"},
  {"bangla": "আল-মুহছী", "english": "AL-MUHSEE"},
  {"bangla": "আল-মুব্দি'", "english": "AL-MUBDI"},
  {"bangla": "আল-মুঈ'দ", "english": "AL-MU’ID"},
  {"bangla": "আল-মুহ'য়ী", "english": "AL-MUHYEE"},
  {"bangla": "আল-মুমীত", "english": "AL-MUMEET"},
  {"bangla": "আল-হাইয়্যু", "english": "AL-HAYY"},
  {"bangla": "আল-ক্বাইয়্যুম", "english": "AL-QAYYOOM"},
  {"bangla": "আল-ওয়াজিদ", "english": "AL-WAAJID"},
  {"bangla": "আল-মুহীত", "english": "AL-MUHIT"},
  {"bangla": "আল-ওয়াহি'দ", "english": "AL-WAAHID"},
  {"bangla": "আল-আহাদ", "english": "AL-AHAD"},
  {"bangla": "আছ্-ছমাদ", "english": "AS-SAMAD"},
  {"bangla": "আল-ক্বদির", "english": "AL-QADIR"},
  {"bangla": "আল-মুক্ব্তাদির", "english": "AL-MUQTADIR"},
  {"bangla": "আল-মুক্বদ্দিম", "english": "AL-MUQADDIM"},
  {"bangla": "আল-মুয়াক্খির", "english": "AL-MU’AKHKHIR"},
  {"bangla": "আল-আউয়াল", "english": "AL-AWWAL"},
  {"bangla": "আল-আখির", "english": "AL-AAKHIR"},
  {"bangla": "আজ-জ'হির", "english": "AZ-JHAAHIR"},
  {"bangla": "আল-বাত্বিন", "english": "AL-BAATIN"},
  {"bangla": "আল-ওয়ালি", "english": "AL-WAALI"},
  {"bangla": "আল-মুতাআ'লি", "english": "AL-MUTA’ALI"},
  {"bangla": "আল-বার্", "english": "AL-BARR"},
  {"bangla": "আত্-তাওয়াব", "english": "AT-TAWWAB"},
  {"bangla": "আল-মুনতাক্বিম", "english": "AL-MUNTAQIM"},
  {"bangla": "আল-আ'ফঊ", "english": "AL-‘AFUWW"},
  {"bangla": "আর-রউফ", "english": "AR-RA’OOF"},
  {"bangla": "মালিকুল-মুলক", "english": "MAALIK-UL-MULK"},
  {"bangla": "যুল-জালালি-ওয়াল-ইকরাম", "english": "DHUL-JALAALI WAL-IKRAAM"},
  {"bangla": "আল-মুক্ব্সিত", "english": "AL-MUQSIT"},
  {"bangla": "আল-জামিই'", "english": "AL-JAAMI’"},
  {"bangla": "আল-গণিই'", "english": "AL-GHANIYY"},
  {"bangla": "আল-মুগণিই'", "english": "AL-MUGHNI"},
  {"bangla": "আল-মানিই'", "english": "AL-MANI’"},
  {"bangla": "আয্-যর", "english": "AD-DHARR"},
  {"bangla": "আন্-নাফিই'", "english": "AN-NAFI’"},
  {"bangla": "আন্-নূর", "english": "AN-NUR"},
  {"bangla": "আল-হাদী", "english": "AL-HAADI"},
  {"bangla": "আল-বাদীই'", "english": "AL-BADEE’"},
  {"bangla": "আল-বাক্বী", "english": "AL-BAAQI"},
  {"bangla": "আল-ওয়ারিস'", "english": "AL-WAARITH"},
  {"bangla": "আর-রাশীদ", "english": "AR-RASHEED"},
  {"bangla": "আস-সবুর", "english": "AS-SABOOR"},
];
List<Map<String, String>> allah99NamesMeaning = [
  {"bangla": "পরম দয়ালু, পরম করুণাময়, সবচেয়ে দয়ালু, কল্যাণময়", "english": "The Exceedingly Compassionate, Beneficent, Gracious (to all of humanity and all creatures)"},
  {"bangla": "অতিশয়-মেহেরবান, অতি দয়ালু", "english": "The Exceedingly Merciful"},
  {"bangla": "সর্বকর্তৃত্বময়, অধিপতি, মালিক", "english": "The King, The Sovereign"},
  {"bangla": "নিষ্কলুষ, অতি পবিত্র", "english": "The Holy, The Divine, The Pure, The Purifier"},
  {"bangla": "নিরাপত্তা-দানকারী, শান্তি-দানকারী, ত্রাণকর্তা, দোষমুক্ত", "english": "The Peace, The Source of Peace and Safety"},
  {"bangla": "নিরাপত্তা ও ঈমান দানকারী, জামিনদার, সত্য ঘোষণাকারী", "english": "The granter of security"},
  {"bangla": "পরিপূর্ন রক্ষণাবেক্ষণকারী, রক্ষক, অভিভাবক, প্রতিপালনকারী", "english": "The Controller"},
  {"bangla": "পরাক্রমশালী, অপরাজেয়, সর্বাধিক সম্মানিত, মহাসম্মানিত", "english": "The Almighty, The Invulnerable, The Honorable"},
  {"bangla": "দুর্নিবার, মহাপ্রতাপশালী, অতীব মহিমান্বিত", "english": "The Irresistible, The Compeller"},
  {"bangla": "নিরঙ্কুশ শ্রেষ্ঠত্বের অধিকারী, সর্বশ্রেষ্ঠ, গৌরবান্বিত, অহংকারী", "english": "The Majestic, The Supreme"},
  {"bangla": "সৃষ্টিকর্তা, সৃষ্টিকারী", "english": "The Creator"},
  {"bangla": "সঠিকভাবে সৃষ্টিকারী", "english": "The Evolver, The Maker"},
  {"bangla": "আকৃতি-দানকারী", "english": "The Fashioner, The Shaper, The Designer"},
  {"bangla": "পরম ক্ষমাশীল, অতি ক্ষমাশীল", "english": "The Repeatedly Forgiving"},
  {"bangla": "কঠোর, মহাপ্রতাবশালী, দমনকারী", "english": "The Subduer"},
  {"bangla": "সবকিছু দানকারী, দানশীল, স্থাপনাকারী", "english": "The Bestower"},
  {"bangla": "রিযিকদাতা", "english": "The Provider"},
  {"bangla": "বিজয়দানকারী, শ্রেষ্ঠ ফয়সালাকারী, প্রারম্ভকারী", "english": "The Opener, The Victory Giver"},
  {"bangla": "সর্বজ্ঞ, মহাজ্ঞানী", "english": "The All-Knowing, Omniscient"},
  {"bangla": "নিয়ন্ত্রণকারী, সরল পথ প্রদর্শনকারী", "english": "The Restrainer, The Straightener"},
  {"bangla": "প্রশস্তকারী", "english": "The Extender / Expander"},
  {"bangla": "অবনতকারী  (কাফির ও মুশরিকদের, অবিশ্বাসীদের অপমানকারী)", "english": "The Abaser, The Humiliator, The Downgrader"},
  {"bangla": "উন্নতকারী, উঁচুকারী", "english": "The Exalter, The Upgrader"},
  {"bangla": "সম্মান-দানকারী", "english": "The Giver of Honor"},
  {"bangla": "(অবিশ্বাসীদের) বেইজ্জতকারী, সম্মান হরণকারী", "english": "The Giver of Dishonor"},
  {"bangla": "সর্বশ্রোতা", "english": "The All-Hearing"},
  {"bangla": "সর্ববিষয়-দর্শনকারী, সর্বদ্রষ্টা", "english": "The All-Seeing"},
  {"bangla": "অটল বিচারক, মহা বিচারপতি, হুকুমদাতা", "english": "The Judge, The Arbitrator"},
  {"bangla": "পরিপূর্ণ-ন্যায়বিচারক, নিখুঁত, ন্যায় বিচারক", "english": "The Utterly Just"},
  {"bangla": "সকল-গোপন-বিষয়ে-অবগত, সূক্ষ্মদর্শী, অমায়িক", "english": "The Gentle, The Subtly Kind"},
  {"bangla": "সকল ব্যাপারে জ্ঞাত, সর্বজ্ঞ", "english": "The All-Aware"},
  {"bangla": "অত্যন্ত ধৈর্যশীল, মহা সহনশীল, প্রশ্রয়দাতা", "english": "The Forbearing, The Indulgent"},
  {"bangla": "সর্বোচ্চ-মর্যাদাশীল, মহা মর্যাদাপূর্ণ, অতি বিরাট", "english": "The Magnificent"},
  {"bangla": "পরম ক্ষমাশীল, মার্জনাকারী, অতীব ক্ষমাশীল", "english": "The Much-Forgiving"},
  {"bangla": "গুনগ্রাহী, সুবিবেচক", "english": "The Grateful"},
  {"bangla": "উচ্চ-মর্যাদাশীল", "english": "The Sublime"},
  {"bangla": "সুমহান, অতি বিরাট", "english": "The Great"},
  {"bangla": "সংরক্ষণকারী", "english": "The Preserver"},
  {"bangla": "সকলের জীবনোপকরণ-দানকারী, সংরক্ষণকারী, লালনপালনকারী", "english": "The Nourisher"},
  {"bangla": "হিসাব-গ্রহণকারী, মহা মীমাংসাকারী", "english": "The Bringer of Judgment"},
  {"bangla": "পরম মর্যাদার অধিকারী, গৌরবান্বিত", "english": "The Majestic"},
  {"bangla": "সুমহান দাতা, মহা সম্মানিত, মহা দয়ালু", "english": "The Bountiful, The Generous"},
  {"bangla": "তত্ত্বাবধায়ক", "english": "The Watchful"},
  {"bangla": "জবাব-দানকারী, সাড়া দানকারী, উত্তরদাতা, দো‘আ কবুলকারী", "english": "The Responsive, The Answerer"},
  {"bangla": "সর্ব-ব্যাপী, অসীম, ব্যাপক", "english": "The Vast, The All-Embracing, The Omnipresent, The Boundless"},
  {"bangla": "পরম-প্রজ্ঞাময়, সুবিজ্ঞ, সুদক্ষ", "english": "The All-Wise"},
  {"bangla": "(বান্দাদের প্রতি) সদয়, প্রেমময়, পরম স্নেহশীল", "english": "The Loving"},
  {"bangla": "সকল-মর্যাদার-অধিকারী, মহিমান্বিত, সম্মানিত", "english": "The All-Glorious, The Majestic"},
  {"bangla": "পুনুরুজ্জীবিতকারী", "english": "The Resurrector"},
  {"bangla": "সর্বজ্ঞ-স্বাক্ষী, প্রত্যক্ষদর্শী", "english": "The Witness"},
  {"bangla": "পরম সত্য", "english": "The Truth, The Reality"},
  {"bangla": "পরম নির্ভরযোগ্য কর্ম-সম্পাদনকারী, তত্ত্বাবধায়ক, সহায় প্রদানকারী, আস্থাভাজন উকিল", "english": "The Trustee, The Dependable, The Advocate"},
  {"bangla": "পরম-শক্তির-অধিকারী", "english": "The Strong"},
  {"bangla": "সুদৃঢ়, সুস্থির", "english": "The Firm, The Steadfast"},
  {"bangla": "অভিভাবক ও সাহায্যকারী", "english": "The Friend, Patron and Helper"},
  {"bangla": "সকল প্রশংসার অধিকারী, সকল প্রশংসার দাবীদার, মহা প্রশংসনীয়", "english": "The All Praiseworthy"},
  {"bangla": "সকল সৃষ্টির ব্যপারে অবগত", "english": "The Accounter, The Numberer of All"},
  {"bangla": "প্রথমবার-সৃষ্টিকর্তা, অগ্রণী, প্রথম প্রবর্তক", "english": "The Originator, The Producer, The Initiator"},
  {"bangla": "পুনরায়-সৃষ্টিকর্তা", "english": "The Restorer, The Reinstater Who Brings Back All"},
  {"bangla": "জীবন-দানকারী", "english": "The Giver of Life"},
  {"bangla": "মৃত্যু-দানকারী", "english": "The Bringer of Death"},
  {"bangla": "চিরঞ্জীব, যার কোন শেষ নেই", "english": "The Living"},
  {"bangla": "সমস্তকিছুর ধারক ও সংরক্ষণকারী", "english": "The Subsisting, The Independent"},
  {"bangla": "অফুরন্ত ভান্ডারের অধিকারী", "english": "The Perceiver, The Finder, The Unfailing"},
  {"bangla": "পরিবেষ্টনকারী, সর্ব বেষ্টনকারী", "english": "The Illustrious, The Magnificent"},
  {"bangla": "এক ও অদ্বিতীয়", "english": "The Unique, The Single"},
  {"bangla": "তিনি সমস্ত পূর্ণতায় একক", "english": "The One, The Indivisible"},
  {"bangla": "অমুখাপেক্ষী,অবিনশ্বর, চিরন্তন, স্বয়ং সম্পূর্ণ", "english": "The Eternal, The Absolute, The Self-Sufficient"},
  {"bangla": "সর্বশক্তিমান, মহা ক্ষমতাধর", "english": "The All-Powerful, He Who is able to do Everything"},
  {"bangla": "নিরঙ্কুশ-সিদ্বান্তের-অধিকারী", "english": "The Determiner, The Dominant"},
  {"bangla": "অগ্রসারক, সর্বাগ্রে সহায়তা প্রদানকারী", "english": "The Expediter, He Who Brings Forward"},
  {"bangla": "অবকাশ দানকারী, বিলম্বকারী", "english": "The Delayer, He Who Puts Far Away"},
  {"bangla": "অনাদি, প্রথম", "english": "The First, The Beginning-less"},
  {"bangla": "অনন্ত, সর্বশেষ", "english": "The Last, The Endless"},
  {"bangla": "সম্পূর্নরূপে-প্রকাশিত, প্রকাশ্য", "english": "The Manifest, The Evident, The Outer"},
  {"bangla": "দৃষ্টি হতে অদৃশ্য, গোপন", "english": "The Hidden, The Unmanifest, The Inner"},
  {"bangla": "সমস্ত কিছুর অভিভাবক", "english": "The Patron, The Protecting Friend, The Friendly Lord"},
  {"bangla": "সৃষ্টির গুনাবলীর উর্দ্ধে", "english": "The Supremely Exalted, The Most High"},
  {"bangla": "পরম-উপকারী, অণুগ্রহশীল, কল্যাণকারী", "english": "The Good, The Beneficent"},
  {"bangla": "তাওবার তাওফিক দানকারী এবং কবুলকারী, ক্ষমাকারী", "english": "The Ever-Returning, Ever-Relenting"},
  {"bangla": "প্রতিশোধ-গ্রহণকারী", "english": "The Avenger"},
  {"bangla": "পরম-উদার, শাস্তি মউকুফকারী, গুনাহ ক্ষমাকারী, পাপ মোচনকারী", "english": "The Pardoner, The Effacer, The Forgiver"},
  {"bangla": "পরম-স্নেহশীল, সদয়, সমবেদনা প্রকাশকারী, দয়াশীল", "english": "The Kind, The Pitying"},
  {"bangla": "সমগ্র জগতের বাদশাহ্", "english": "Owner of all Sovereignty"},
  {"bangla": "মহিমান্বিত ও দয়াবান সত্তা, মহা মর্যাদাবান, মহা মহত্ত্ব ও মহা সম্মানিত", "english": "Lord of Majesty and Generosity"},
  {"bangla": "হকদারের হক-আদায়কারী", "english": "The Equitable, The Requiter"},
  {"bangla": "একত্রকারী, সমবেতকারী", "english": "The Gatherer, The Unifier"},
  {"bangla": "অমুখাপেক্ষী ধনী", "english": "The Rich, The Independent"},
  {"bangla": "পরম-অভাবমোচনকারী, সমৃদ্ধকারী, উদ্ধারকারী", "english": "The Enricher, The Emancipator"},
  {"bangla": "অকল্যাণরোধক, প্রতিরোধকারী, রক্ষাকর্তা, নিষেধকারী, বারণকারী", "english": "The Withholder, The Shielder, The Defender"},
  {"bangla": "ক্ষতিসাধনকারী, যন্ত্রনাদানকারী, উৎপীড়নকারী", "english": "The Distressor, The Harmer, The Afflictor"},
  {"bangla": "কল্যাণকারী, অনুগ্রাহক, উপকারকারী, হিতকারী", "english": "The Propitious, The Benefactor, The Source of Good"},
  {"bangla": "পরম-আলো, আলোক", "english": "The Light"},
  {"bangla": "পথ-প্রদর্শক, হিদায়েতকারী", "english": "The Guide, The Way"},
  {"bangla": "অতুলনীয়", "english": "The Incomparable, The Unattainable, The Beautiful"},
  {"bangla": "চিরস্থায়ী, অবিনশ্বর", "english": "The Immutable, The Infinite, The Everlasting"},
  {"bangla": "উত্তরাধিকারী", "english": "The Heir, The Inheritor of All"},
  {"bangla": "সঠিক পথ-প্রদর্শক, বিচক্ষণ, সচেতন", "english": "The Guide to the Right Path"},
  {"bangla": "অত্যধিক ধৈর্যধারণকারী", "english": "The Timeless, The Patient"}
];

